baseURL = "https://j4c0bs.github.io/"
languageCode = "en-us"
title = "j4c0bs"
theme = "PaperMod"
paginate = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true

[params]
  env = "production"
  description = "Notes on data engineering, software engineering, and AI"
  author = "Jeremy Jacobs"
  DateFormat = "2006-01-02"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false

  [params.homeInfoParams]
    Title = "j4c0bs"
    Content = "Notes on data engineering, software engineering, and AI."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/j4c0bs"

[params.assets]
  disableHLJS = true

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[markup]
  [markup.highlight]
    noClasses = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "onedark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"], ["$", "$"]]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
